/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CustomButton: typeof import('./src/components/CustomButton.vue')['default']
    CustomSelect: typeof import('./src/components/inputs/CustomSelect.vue')['default']
    DragDropList: typeof import('./src/components/DragDropList.vue')['default']
    Input: typeof import('./src/components/inputs/Input.vue')['default']
    InputFile: typeof import('./src/components/inputs/InputFile.vue')['default']
    LinkConstructor: typeof import('./src/components/forms/LinkConstructor.vue')['default']
    Login: typeof import('./src/components/forms/Login.vue')['default']
    Navigation: typeof import('./src/components/Navigation.vue')['default']
    NavigationTabs: typeof import('./src/components/NavigationTabs.vue')['default']
    Notification: typeof import('./src/components/Notification.vue')['default']
    Register: typeof import('./src/components/forms/Register.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    TabContentDetails: typeof import('./src/components/TabContentDetails.vue')['default']
    TabContentLinks: typeof import('./src/components/TabContentLinks.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
