services:
  backend:
    build:
      context: ./backend
      target: prod
    volumes:
      - ./backend:/app
      - ./backend/data:/data
    ports:
      - "8080:8080"
    environment:
      - DB_PATH=${DB_PATH}
      - DB_PORT=${DB_PORT}

  frontend:
    build:
      context: ./frontend
      target: prod
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production
      - VITE_API_BASE_URL=${VITE_API_ENDPOINT}
    command: node dist/index.js
    depends_on:
      - backend

volumes:
  sqlite-data: {}