FROM golang:1.24-alpine

WORKDIR /app
RUN apk add --no-cache git curl sqlite

# Air per hot‑reload
RUN go install github.com/air-verse/air@latest

COPY go.mod go.sum ./
RUN go mod download

COPY . .

# Monta il DB locale via volume
ENV DB_PATH=/data/sqlite.db

# Avvia air
CMD ["air", "-c", ".air.toml"]