FROM golang:1.24-alpine

WORKDIR /app
RUN apk add --no-cache git curl sqlite

RUN go install github.com/air-verse/air@latest

COPY go.mod go.sum ./
RUN go mod download

COPY . .

ENV DB_PATH=/data/sqlite.db

# Avvia air
CMD ["air", "-c", ".air.toml"]